#!/bin/sh
#
# Install the meteo init script:
#
#   sudo cp meteo /etc/init.d/meteo
#   sudo update-rc.d meteo defaults 99 01
#   sudo service meteo start
# 
### BEGIN INIT INFO
# Provides:          meteo
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: meteo
# Description:       Vagrant starts a docker container with the meteo script.
### END INIT INFO

METEO_DIR="/home/user/meteo"
METEO_USER="user"

case "${1}" in
start)
    su -c "cd ${METEO_DIR}; vagrant up" ${METEO_USER}
;;
stop)
    su -c "cd ${METEO_DIR}; vagrant halt" ${METEO_USER}
;;
*)
    echo "usage: ${0} [start|stop]"
esac

exit 0

